# Generated by Django 4.0.5 on 2022-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='released',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
