# Generated by Django 4.0.5 on 2022-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapi', '0002_movies_cover_movies_description_movies_is_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
