# Generated by Django 4.0.5 on 2022-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapi', '0003_alter_movies_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='released',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
